//users
POST http://localhost:3000/users/create HTTP/1.1
content-type: application/json

{ "username" : "youone" , 
   "email" : "youone@gmail.com", 
   "password": 123 
}

###
POST http://localhost:3001/users/login HTTP/1.1
content-type: application/json

{ "username" : "youone" , 
   "password": 123
}

###
POST http://localhost:3000/users/67062dfdbe55c04d42296a71/friend-request/6703ad940701213a547ac304 HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/users/6703ad940701213a547ac304/friends HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/users/67027bc5785a04d1ababc37f/friend-requests HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/users/67027b93785a04d1ababc37d/sent-friend-requests HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/users/67027b93785a04d1ababc37d/accept-friend/6703ad940701213a547ac304 HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/users/6703ad940701213a547ac304/profile HTTP/1.1
content-type: application/json

// end users

//chats
###
POST http://localhost:3001/chats/send HTTP/1.1
content-type: application/json

{ "from" : "67027bc5785a04d1ababc37f" , 
   "to" : "67027b93785a04d1ababc37d", 
   "message": "hallo 7D from 7F"
}

###
GET http://localhost:3001/chats/recent/67027b93785a04d1ababc37d HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/chats/current/6703ad940701213a547ac304/67027b93785a04d1ababc37d HTTP/1.1
content-type: application/json

//end chat


